language: go
go:
  - 1.15.x
addons:
  apt:
    packages:
      - libpcap0.8-dev
install:
  - true # prevent travis from installing dependencies now
script:
  - go get -u github.com/rakyll/statik
  - make static
  - go test -v ./...
  - tar czf traffic-mirroring-${TRAVIS_TAG}.tar.gz traffic-mirroring
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_OAUTH_TOKEN
  file: "*.tar.gz"
  file_glob: true
  skip_cleanup: true
  on:
    repo: criteo/traffic-mirroring
    tags: true

